### ISSUE TITLE
Pplot errors

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#172] opened 2018-04-24 17:48 UTC
Pplot takes too long to run and plots an awful lot of text at the top of the plot 

MSE<-runMSE(testOM,MP="AvC")
Pplot(MSE)

**Comment by quang-huynh** [comment] 2018-04-24 23:16
Pplot runs very quickly for me, so I'm not sure where the problem is.

For some reason, there's an issue with deparse(substitute(x)) which results in the weird title. I've replaced with deparse(quote(x)) which appears to be working for now. I'll push this change.

**Comment by AdrianHordyk** [comment] 2018-05-01 20:33
appears to be fixed, though the naming of the plots is still a bit weird. Closing issue

**Closed by AdrianHordyk** 2018-05-01 20:33 UTC
Labels: bug
