### ISSUE TITLE
DLMextra() bug

### ISSUE THREAD

**Issue by tcarruth** [DLMtool/DLMtool#234] opened 2018-12-06 19:20 UTC
From a fresh R session this is what I get:

> library(DLMtool)
Loading required package: snowfall
Loading required package: snow
> DLMextra()

Downloading 'DLMextra' from GitHub
Error in if (tt) { : argument is not interpretable as logical

**Comment by AdrianHordyk** [comment] 2018-12-10 20:47
This is caused by changes in the latest version of devtools. Issue has been fixed in the dev version of DLMtool

**Closed** 2019-01-22 23:05 UTC
Labels: bug
